environment: dev

# path to the workers dierectory 
workers:
  path: /Users/aakashbasnet/development/python/projects/mahuri_hive/workers

# path to the worksapace where the files are written durin the run process
workspace: 
    path: /Users/aakashbasnet/development/python/projects/mahuri_hive/test/workspace
# db info

database:
    test: test@dgad@ak:22
    test2: aakfjl@akjfka:33

logger:
    path: /Users/aakashbasnet/development/python/projects/mahuri_hive/test/logs 
    test: fasfasfasa@Afafa
