feed_name: mero_lagani
duties:
- name: extract
  url: https://merolagani.com/CompanyDetail.aspx?symbol={symbol}
  symbols: [NIFRA, CGH]
  class_name: feed.Extract
  depends: []

- name: save
  class_name: feed.Save
  depends: [extract]

- name: transform
  class_name: feed.Transform
  depends: [extract]

- name: load
  database: honeycombs
  class_name: feed.Load
  depends: [transform]


    