flower_name: mero_lagani
duties:
- name: extract
  url: https://merolagani.com/CompanyDetail.aspx?symbol={symbol}
  symbols: [NIFRA, CGH]
  depends: []
- name: transform
  depends: [extract]
- name: load
  database: honeycombs
  depends: [transform]


    