feed_name: mero_lagani
duties:
- name: extract
  url: https://merolagani.com/CompanyDetail.aspx?symbol={symbol}
  symbols: [NIFRA, CGH]
  class: feed.extract
  depends: []

- name: save
  class: feed.save
  depends: [extract]

- name: transform
  class: feed.transform
  depends: [extract]

- name: load
  database: honeycombs
  class: feed.load
  depends: [transform]


    